name = "ll-cockpit-design"
main = ".open-next/worker.js"
compatibility_date = "2026-05-13"
compatibility_flags = ["nodejs_compat"]
assets = { directory = ".open-next/assets", binding = "ASSETS" }

[[d1_databases]]
binding = "DB"
database_name = "ll-cockpit-db"
database_id = "831eeccf-60bc-4378-8a3b-71dfb910756e"

[[r2_buckets]]
binding = "R2"
bucket_name = "ll-cockpit-r2"
